# Generated by Django 4.2 on 2023-05-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0003_remove_issue_created_by_remove_issue_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="attachment_file",
            field=models.FileField(max_length=1000, upload_to="documents/"),
        ),
    ]
