# Generated by Django 4.2 on 2023-05-09 06:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0006_alter_attachment_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="index",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issuetype",
            name="icon",
            field=models.ImageField(
                blank=True,
                max_length=1000,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="icons/",
            ),
        ),
        migrations.AlterField(
            model_name="priority",
            name="icon",
            field=models.ImageField(
                blank=True,
                max_length=1000,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="icons/",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="icon",
            field=models.ImageField(
                blank=True,
                max_length=1000,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="icons/",
            ),
        ),
    ]
