# Generated by Django 4.2 on 2023-05-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0007_issue_index_alter_issuetype_icon_alter_priority_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="comment_text",
        ),
    ]
