# Generated by Django 4.2.1 on 2023-05-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0010_alter_attachment_attachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="updated_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
