# Generated by Django 4.2 on 2023-04-13 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_role"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role",
                to="user.role",
            ),
            preserve_default=False,
        ),
    ]
