# Generated by Django 4.2 on 2023-04-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_team_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="stat_date",
            new_name="start_date",
        ),
    ]
