# Generated by Django 4.2 on 2023-04-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_rename_stat_date_project_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
