# Generated by Django 4.2 on 2023-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_role_table_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.TextField(),
        ),
    ]
