# Generated by Django 4.2 on 2023-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAvtar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, max_length=1000, upload_to="icons/"),
                ),
            ],
            options={
                "db_table": "avtar",
            },
        ),
    ]
