# Generated by Django 4.2 on 2023-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_useravtar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useravtar",
            name="icon",
        ),
        migrations.AddField(
            model_name="useravtar",
            name="avtar",
            field=models.ImageField(blank=True, max_length=1000, upload_to="avtar/"),
        ),
    ]
