# Generated by Django 4.2 on 2023-04-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_delete_useravtar"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
