# Generated by Django 4.2.1 on 2023-05-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_profileavtar_image_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
